### ISSUE TITLE
graphql posts query only returns latest 10 posts

### ISSUE THREAD

**Issue by aditditto** [laikaklinikhewan/web-laika#24]
Jadinya post lama ga ke build di /artikel/[slug]???

**Comment by aditditto** [comment]
contoh:
```
query MyQuery {
  posts {
    nodes {
      slug
    }
  }
}
```

**Comment by aditditto** [comment]
ow ternyata emang dibatasin gitu biar querynya ga kegedean?? cekidot
https://spectrum.chat/wpgraphql/general/best-way-to-pull-all-posts-for-next-js-static-export~fe5cd57c-3728-4e0d-b94c-c25c0099ac50

**Comment by aditditto** [comment]
ow ternyata emang dibatasin gitu biar querynya ga kegedean?? cekidot @leocardhio 
https://spectrum.chat/wpgraphql/general/best-way-to-pull-all-posts-for-next-js-static-export~fe5cd57c-3728-4e0d-b94c-c25c0099ac50

**Comment by leocardhio** [comment]
bahaya juga ga si kalo gini? ntar staf nya ga kefetch
